// Code generated by entc, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"medical_system/database/models/prescription"
	"medical_system/database/models/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrescriptionCreate is the builder for creating a Prescription entity.
type PrescriptionCreate struct {
	config
	mutation *PrescriptionMutation
	hooks    []Hook
}

// SetDoctorID sets the "doctor_id" field.
func (pc *PrescriptionCreate) SetDoctorID(i int64) *PrescriptionCreate {
	pc.mutation.SetDoctorID(i)
	return pc
}

// SetPatientNationalCode sets the "patient_national_code" field.
func (pc *PrescriptionCreate) SetPatientNationalCode(s string) *PrescriptionCreate {
	pc.mutation.SetPatientNationalCode(s)
	return pc
}

// SetDrugsCommaSeperated sets the "drugs_comma_seperated" field.
func (pc *PrescriptionCreate) SetDrugsCommaSeperated(s string) *PrescriptionCreate {
	pc.mutation.SetDrugsCommaSeperated(s)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PrescriptionCreate) SetCreatedAt(t time.Time) *PrescriptionCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableCreatedAt(t *time.Time) *PrescriptionCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (pc *PrescriptionCreate) SetUsersID(id int) *PrescriptionCreate {
	pc.mutation.SetUsersID(id)
	return pc
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableUsersID(id *int) *PrescriptionCreate {
	if id != nil {
		pc = pc.SetUsersID(*id)
	}
	return pc
}

// SetUsers sets the "users" edge to the User entity.
func (pc *PrescriptionCreate) SetUsers(u *User) *PrescriptionCreate {
	return pc.SetUsersID(u.ID)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (pc *PrescriptionCreate) Mutation() *PrescriptionMutation {
	return pc.mutation
}

// Save creates the Prescription in the database.
func (pc *PrescriptionCreate) Save(ctx context.Context) (*Prescription, error) {
	var (
		err  error
		node *Prescription
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrescriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("models: uninitialized hook (forgotten import models/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PrescriptionCreate) SaveX(ctx context.Context) *Prescription {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PrescriptionCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PrescriptionCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PrescriptionCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := prescription.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PrescriptionCreate) check() error {
	if _, ok := pc.mutation.DoctorID(); !ok {
		return &ValidationError{Name: "doctor_id", err: errors.New(`models: missing required field "doctor_id"`)}
	}
	if _, ok := pc.mutation.PatientNationalCode(); !ok {
		return &ValidationError{Name: "patient_national_code", err: errors.New(`models: missing required field "patient_national_code"`)}
	}
	if _, ok := pc.mutation.DrugsCommaSeperated(); !ok {
		return &ValidationError{Name: "drugs_comma_seperated", err: errors.New(`models: missing required field "drugs_comma_seperated"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`models: missing required field "created_at"`)}
	}
	return nil
}

func (pc *PrescriptionCreate) sqlSave(ctx context.Context) (*Prescription, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PrescriptionCreate) createSpec() (*Prescription, *sqlgraph.CreateSpec) {
	var (
		_node = &Prescription{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: prescription.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prescription.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.DoctorID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: prescription.FieldDoctorID,
		})
		_node.DoctorID = value
	}
	if value, ok := pc.mutation.PatientNationalCode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldPatientNationalCode,
		})
		_node.PatientNationalCode = value
	}
	if value, ok := pc.mutation.DrugsCommaSeperated(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldDrugsCommaSeperated,
		})
		_node.DrugsCommaSeperated = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: prescription.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := pc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.UsersTable,
			Columns: []string{prescription.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_prescriptions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PrescriptionCreateBulk is the builder for creating many Prescription entities in bulk.
type PrescriptionCreateBulk struct {
	config
	builders []*PrescriptionCreate
}

// Save creates the Prescription entities in the database.
func (pcb *PrescriptionCreateBulk) Save(ctx context.Context) ([]*Prescription, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Prescription, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrescriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PrescriptionCreateBulk) SaveX(ctx context.Context) []*Prescription {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PrescriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PrescriptionCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
