// Code generated by entc, DO NOT EDIT.

package models

import (
	"context"
	"fmt"
	"medical_system/database/models/predicate"
	"medical_system/database/models/prescription"
	"medical_system/database/models/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrescriptionUpdate is the builder for updating Prescription entities.
type PrescriptionUpdate struct {
	config
	hooks    []Hook
	mutation *PrescriptionMutation
}

// Where appends a list predicates to the PrescriptionUpdate builder.
func (pu *PrescriptionUpdate) Where(ps ...predicate.Prescription) *PrescriptionUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetDoctorID sets the "doctor_id" field.
func (pu *PrescriptionUpdate) SetDoctorID(i int64) *PrescriptionUpdate {
	pu.mutation.ResetDoctorID()
	pu.mutation.SetDoctorID(i)
	return pu
}

// AddDoctorID adds i to the "doctor_id" field.
func (pu *PrescriptionUpdate) AddDoctorID(i int64) *PrescriptionUpdate {
	pu.mutation.AddDoctorID(i)
	return pu
}

// SetPatientNationalCode sets the "patient_national_code" field.
func (pu *PrescriptionUpdate) SetPatientNationalCode(s string) *PrescriptionUpdate {
	pu.mutation.SetPatientNationalCode(s)
	return pu
}

// SetDrugsCommaSeperated sets the "drugs_comma_seperated" field.
func (pu *PrescriptionUpdate) SetDrugsCommaSeperated(s string) *PrescriptionUpdate {
	pu.mutation.SetDrugsCommaSeperated(s)
	return pu
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (pu *PrescriptionUpdate) SetUsersID(id int) *PrescriptionUpdate {
	pu.mutation.SetUsersID(id)
	return pu
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (pu *PrescriptionUpdate) SetNillableUsersID(id *int) *PrescriptionUpdate {
	if id != nil {
		pu = pu.SetUsersID(*id)
	}
	return pu
}

// SetUsers sets the "users" edge to the User entity.
func (pu *PrescriptionUpdate) SetUsers(u *User) *PrescriptionUpdate {
	return pu.SetUsersID(u.ID)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (pu *PrescriptionUpdate) Mutation() *PrescriptionMutation {
	return pu.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (pu *PrescriptionUpdate) ClearUsers() *PrescriptionUpdate {
	pu.mutation.ClearUsers()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PrescriptionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrescriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("models: uninitialized hook (forgotten import models/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PrescriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PrescriptionUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PrescriptionUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PrescriptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   prescription.Table,
			Columns: prescription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prescription.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.DoctorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: prescription.FieldDoctorID,
		})
	}
	if value, ok := pu.mutation.AddedDoctorID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: prescription.FieldDoctorID,
		})
	}
	if value, ok := pu.mutation.PatientNationalCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldPatientNationalCode,
		})
	}
	if value, ok := pu.mutation.DrugsCommaSeperated(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldDrugsCommaSeperated,
		})
	}
	if pu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.UsersTable,
			Columns: []string{prescription.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.UsersTable,
			Columns: []string{prescription.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// PrescriptionUpdateOne is the builder for updating a single Prescription entity.
type PrescriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrescriptionMutation
}

// SetDoctorID sets the "doctor_id" field.
func (puo *PrescriptionUpdateOne) SetDoctorID(i int64) *PrescriptionUpdateOne {
	puo.mutation.ResetDoctorID()
	puo.mutation.SetDoctorID(i)
	return puo
}

// AddDoctorID adds i to the "doctor_id" field.
func (puo *PrescriptionUpdateOne) AddDoctorID(i int64) *PrescriptionUpdateOne {
	puo.mutation.AddDoctorID(i)
	return puo
}

// SetPatientNationalCode sets the "patient_national_code" field.
func (puo *PrescriptionUpdateOne) SetPatientNationalCode(s string) *PrescriptionUpdateOne {
	puo.mutation.SetPatientNationalCode(s)
	return puo
}

// SetDrugsCommaSeperated sets the "drugs_comma_seperated" field.
func (puo *PrescriptionUpdateOne) SetDrugsCommaSeperated(s string) *PrescriptionUpdateOne {
	puo.mutation.SetDrugsCommaSeperated(s)
	return puo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (puo *PrescriptionUpdateOne) SetUsersID(id int) *PrescriptionUpdateOne {
	puo.mutation.SetUsersID(id)
	return puo
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (puo *PrescriptionUpdateOne) SetNillableUsersID(id *int) *PrescriptionUpdateOne {
	if id != nil {
		puo = puo.SetUsersID(*id)
	}
	return puo
}

// SetUsers sets the "users" edge to the User entity.
func (puo *PrescriptionUpdateOne) SetUsers(u *User) *PrescriptionUpdateOne {
	return puo.SetUsersID(u.ID)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (puo *PrescriptionUpdateOne) Mutation() *PrescriptionMutation {
	return puo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (puo *PrescriptionUpdateOne) ClearUsers() *PrescriptionUpdateOne {
	puo.mutation.ClearUsers()
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PrescriptionUpdateOne) Select(field string, fields ...string) *PrescriptionUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Prescription entity.
func (puo *PrescriptionUpdateOne) Save(ctx context.Context) (*Prescription, error) {
	var (
		err  error
		node *Prescription
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrescriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("models: uninitialized hook (forgotten import models/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PrescriptionUpdateOne) SaveX(ctx context.Context) *Prescription {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PrescriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PrescriptionUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PrescriptionUpdateOne) sqlSave(ctx context.Context) (_node *Prescription, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   prescription.Table,
			Columns: prescription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prescription.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Prescription.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prescription.FieldID)
		for _, f := range fields {
			if !prescription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != prescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.DoctorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: prescription.FieldDoctorID,
		})
	}
	if value, ok := puo.mutation.AddedDoctorID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: prescription.FieldDoctorID,
		})
	}
	if value, ok := puo.mutation.PatientNationalCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldPatientNationalCode,
		})
	}
	if value, ok := puo.mutation.DrugsCommaSeperated(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prescription.FieldDrugsCommaSeperated,
		})
	}
	if puo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.UsersTable,
			Columns: []string{prescription.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.UsersTable,
			Columns: []string{prescription.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Prescription{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
